CRITICAL - 2023-05-30 10:41:39 --> syntax error, unexpected token ";", expecting "]"
in APPPATH\Config\Filters.php on line 65.
 1 SYSTEMPATH\Autoloader\Autoloader.php(289): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs\\codeigniter4\\app\\Config\\Filters.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(267): CodeIgniter\Autoloader\Autoloader->loadInNamespace('Config\\Filters')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('Config\\Filters')
 4 SYSTEMPATH\Config\Factories.php(155): class_exists('Config\\Filters')
 5 SYSTEMPATH\Config\Factories.php(125): CodeIgniter\Config\Factories::locateClass([...], 'Filters')
 6 SYSTEMPATH\Common.php(216): CodeIgniter\Config\Factories::__callStatic('config', [])
 7 SYSTEMPATH\Config\Services.php(285): config('Filters')
 8 SYSTEMPATH\Config\BaseService.php(252): CodeIgniter\Config\Services::filters(null, false)
 9 SYSTEMPATH\Config\BaseService.php(193): CodeIgniter\Config\BaseService::__callStatic('filters', [...])
10 SYSTEMPATH\Config\Services.php(282): CodeIgniter\Config\BaseService::getSharedInstance('filters', null)
11 SYSTEMPATH\Config\BaseService.php(252): CodeIgniter\Config\Services::filters()
12 SYSTEMPATH\CodeIgniter.php(455): CodeIgniter\Config\BaseService::__callStatic('filters', [])
13 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
14 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-30 10:42:11 --> syntax error, unexpected token ";", expecting "]"
in APPPATH\Config\Filters.php on line 64.
 1 SYSTEMPATH\Autoloader\Autoloader.php(289): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs\\codeigniter4\\app\\Config\\Filters.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(267): CodeIgniter\Autoloader\Autoloader->loadInNamespace('Config\\Filters')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('Config\\Filters')
 4 SYSTEMPATH\Config\Factories.php(155): class_exists('Config\\Filters')
 5 SYSTEMPATH\Config\Factories.php(125): CodeIgniter\Config\Factories::locateClass([...], 'Filters')
 6 SYSTEMPATH\Common.php(216): CodeIgniter\Config\Factories::__callStatic('config', [])
 7 SYSTEMPATH\Config\Services.php(285): config('Filters')
 8 SYSTEMPATH\Config\BaseService.php(252): CodeIgniter\Config\Services::filters(null, false)
 9 SYSTEMPATH\Config\BaseService.php(193): CodeIgniter\Config\BaseService::__callStatic('filters', [...])
10 SYSTEMPATH\Config\Services.php(282): CodeIgniter\Config\BaseService::getSharedInstance('filters', null)
11 SYSTEMPATH\Config\BaseService.php(252): CodeIgniter\Config\Services::filters()
12 SYSTEMPATH\CodeIgniter.php(455): CodeIgniter\Config\BaseService::__callStatic('filters', [])
13 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
14 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-30 10:42:12 --> syntax error, unexpected token ";", expecting "]"
in APPPATH\Config\Filters.php on line 64.
 1 SYSTEMPATH\Autoloader\Autoloader.php(289): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs\\codeigniter4\\app\\Config\\Filters.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(267): CodeIgniter\Autoloader\Autoloader->loadInNamespace('Config\\Filters')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('Config\\Filters')
 4 SYSTEMPATH\Config\Factories.php(155): class_exists('Config\\Filters')
 5 SYSTEMPATH\Config\Factories.php(125): CodeIgniter\Config\Factories::locateClass([...], 'Filters')
 6 SYSTEMPATH\Common.php(216): CodeIgniter\Config\Factories::__callStatic('config', [])
 7 SYSTEMPATH\Config\Services.php(285): config('Filters')
 8 SYSTEMPATH\Config\BaseService.php(252): CodeIgniter\Config\Services::filters(null, false)
 9 SYSTEMPATH\Config\BaseService.php(193): CodeIgniter\Config\BaseService::__callStatic('filters', [...])
10 SYSTEMPATH\Config\Services.php(282): CodeIgniter\Config\BaseService::getSharedInstance('filters', null)
11 SYSTEMPATH\Config\BaseService.php(252): CodeIgniter\Config\Services::filters()
12 SYSTEMPATH\CodeIgniter.php(455): CodeIgniter\Config\BaseService::__callStatic('filters', [])
13 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
14 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-30 10:42:20 --> Unclosed '[' on line 63 does not match '}'
in APPPATH\Config\Filters.php on line 65.
 1 SYSTEMPATH\Autoloader\Autoloader.php(289): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs\\codeigniter4\\app\\Config\\Filters.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(267): CodeIgniter\Autoloader\Autoloader->loadInNamespace('Config\\Filters')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('Config\\Filters')
 4 SYSTEMPATH\Config\Factories.php(155): class_exists('Config\\Filters')
 5 SYSTEMPATH\Config\Factories.php(125): CodeIgniter\Config\Factories::locateClass([...], 'Filters')
 6 SYSTEMPATH\Common.php(216): CodeIgniter\Config\Factories::__callStatic('config', [])
 7 SYSTEMPATH\Config\Services.php(285): config('Filters')
 8 SYSTEMPATH\Config\BaseService.php(252): CodeIgniter\Config\Services::filters(null, false)
 9 SYSTEMPATH\Config\BaseService.php(193): CodeIgniter\Config\BaseService::__callStatic('filters', [...])
10 SYSTEMPATH\Config\Services.php(282): CodeIgniter\Config\BaseService::getSharedInstance('filters', null)
11 SYSTEMPATH\Config\BaseService.php(252): CodeIgniter\Config\Services::filters()
12 SYSTEMPATH\CodeIgniter.php(455): CodeIgniter\Config\BaseService::__callStatic('filters', [])
13 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
14 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-30 10:42:43 --> syntax error, unexpected token "}", expecting "," or ";"
in APPPATH\Config\Filters.php on line 66.
 1 SYSTEMPATH\Autoloader\Autoloader.php(289): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs\\codeigniter4\\app\\Config\\Filters.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(267): CodeIgniter\Autoloader\Autoloader->loadInNamespace('Config\\Filters')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('Config\\Filters')
 4 SYSTEMPATH\Config\Factories.php(155): class_exists('Config\\Filters')
 5 SYSTEMPATH\Config\Factories.php(125): CodeIgniter\Config\Factories::locateClass([...], 'Filters')
 6 SYSTEMPATH\Common.php(216): CodeIgniter\Config\Factories::__callStatic('config', [])
 7 SYSTEMPATH\Config\Services.php(285): config('Filters')
 8 SYSTEMPATH\Config\BaseService.php(252): CodeIgniter\Config\Services::filters(null, false)
 9 SYSTEMPATH\Config\BaseService.php(193): CodeIgniter\Config\BaseService::__callStatic('filters', [...])
10 SYSTEMPATH\Config\Services.php(282): CodeIgniter\Config\BaseService::getSharedInstance('filters', null)
11 SYSTEMPATH\Config\BaseService.php(252): CodeIgniter\Config\Services::filters()
12 SYSTEMPATH\CodeIgniter.php(455): CodeIgniter\Config\BaseService::__callStatic('filters', [])
13 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
14 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-30 10:43:22 --> Attempt to read property "user_password" on null
in APPPATH\Controllers\Auth.php on line 21.
 1 APPPATH\Controllers\Auth.php(21): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "user_password" on null', 'C:\\xampp\\htdocs\\codeigniter4\\app\\Controllers\\Auth.php', 21)
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-30 10:44:41 --> Attempt to read property "user_password" on null
in APPPATH\Controllers\Auth.php on line 21.
 1 APPPATH\Controllers\Auth.php(21): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "user_password" on null', 'C:\\xampp\\htdocs\\codeigniter4\\app\\Controllers\\Auth.php', 21)
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-30 10:44:50 --> Attempt to read property "user_password" on null
in APPPATH\Controllers\Auth.php on line 21.
 1 APPPATH\Controllers\Auth.php(21): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "user_password" on null', 'C:\\xampp\\htdocs\\codeigniter4\\app\\Controllers\\Auth.php', 21)
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-30 10:45:12 --> Attempt to read property "user_password" on null
in APPPATH\Controllers\Auth.php on line 21.
 1 APPPATH\Controllers\Auth.php(21): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "user_password" on null', 'C:\\xampp\\htdocs\\codeigniter4\\app\\Controllers\\Auth.php', 21)
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-30 10:45:29 --> Trying to access array offset on value of type null
in APPPATH\Controllers\Auth.php on line 21.
 1 APPPATH\Controllers\Auth.php(21): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to access array offset on value of type null', 'C:\\xampp\\htdocs\\codeigniter4\\app\\Controllers\\Auth.php', 21)
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-30 10:47:25 --> "authfilter" filter must have a matching alias defined.
in SYSTEMPATH\Filters\Filters.php on line 493.
 1 SYSTEMPATH\Filters\Filters.php(493): CodeIgniter\Filters\Exceptions\FilterException::forNoAlias('authfilter')
 2 SYSTEMPATH\Filters\Filters.php(243): CodeIgniter\Filters\Filters->processAliasesToClass('before')
 3 SYSTEMPATH\Filters\Filters.php(163): CodeIgniter\Filters\Filters->initialize('management/admin')
 4 SYSTEMPATH\CodeIgniter.php(473): CodeIgniter\Filters\Filters->run('management/admin', 'before')
 5 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-30 10:57:03 --> Undefined variable $user_name
in APPPATH\Views\backend\login.php on line 13.
 1 APPPATH\Views\backend\login.php(13): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $user_name', 'C:\\xampp\\htdocs\\codeigniter4\\app\\Views\\backend\\login.php', 13)
 2 SYSTEMPATH\View\View.php(213): include('C:\\xampp\\htdocs\\codeigniter4\\app\\Views\\backend\\login.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('backend/login', [], true)
 5 APPPATH\Controllers\Auth.php(26): view('backend/login')
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-30 10:57:03 --> Undefined variable $user_name
in APPPATH\Views\backend\login.php on line 13.
 1 APPPATH\Views\backend\login.php(13): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $user_name', 'C:\\xampp\\htdocs\\codeigniter4\\app\\Views\\backend\\login.php', 13)
 2 SYSTEMPATH\View\View.php(213): include('C:\\xampp\\htdocs\\codeigniter4\\app\\Views\\backend\\login.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('backend/login', [], true)
 5 APPPATH\Controllers\Auth.php(26): view('backend/login')
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-30 10:57:03 --> Undefined variable $user_name
in APPPATH\Views\backend\login.php on line 13.
 1 APPPATH\Views\backend\login.php(13): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $user_name', 'C:\\xampp\\htdocs\\codeigniter4\\app\\Views\\backend\\login.php', 13)
 2 SYSTEMPATH\View\View.php(213): include('C:\\xampp\\htdocs\\codeigniter4\\app\\Views\\backend\\login.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('backend/login', [], true)
 5 APPPATH\Controllers\Auth.php(26): view('backend/login')
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-30 10:57:04 --> Undefined variable $user_name
in APPPATH\Views\backend\login.php on line 13.
 1 APPPATH\Views\backend\login.php(13): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $user_name', 'C:\\xampp\\htdocs\\codeigniter4\\app\\Views\\backend\\login.php', 13)
 2 SYSTEMPATH\View\View.php(213): include('C:\\xampp\\htdocs\\codeigniter4\\app\\Views\\backend\\login.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('backend/login', [], true)
 5 APPPATH\Controllers\Auth.php(26): view('backend/login')
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-30 10:57:04 --> Undefined variable $user_name
in APPPATH\Views\backend\login.php on line 13.
 1 APPPATH\Views\backend\login.php(13): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $user_name', 'C:\\xampp\\htdocs\\codeigniter4\\app\\Views\\backend\\login.php', 13)
 2 SYSTEMPATH\View\View.php(213): include('C:\\xampp\\htdocs\\codeigniter4\\app\\Views\\backend\\login.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('backend/login', [], true)
 5 APPPATH\Controllers\Auth.php(26): view('backend/login')
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-30 10:59:01 --> Undefined variable $auth
in APPPATH\Views\backend\login.php on line 14.
 1 APPPATH\Views\backend\login.php(14): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $auth', 'C:\\xampp\\htdocs\\codeigniter4\\app\\Views\\backend\\login.php', 14)
 2 SYSTEMPATH\View\View.php(213): include('C:\\xampp\\htdocs\\codeigniter4\\app\\Views\\backend\\login.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('backend/login', [], true)
 5 APPPATH\Controllers\Auth.php(26): view('backend/login')
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-30 10:59:49 --> Attempt to read property "user_password" on array
in APPPATH\Controllers\Auth.php on line 21.
 1 APPPATH\Controllers\Auth.php(21): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "user_password" on array', 'C:\\xampp\\htdocs\\codeigniter4\\app\\Controllers\\Auth.php', 21)
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-30 11:00:25 --> Undefined variable $auth
in APPPATH\Controllers\Auth.php on line 26.
 1 APPPATH\Controllers\Auth.php(26): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $auth', 'C:\\xampp\\htdocs\\codeigniter4\\app\\Controllers\\Auth.php', 26)
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-30 11:02:20 --> Undefined property: App\Controllers\Auth::$session
in APPPATH\Controllers\Auth.php on line 23.
 1 APPPATH\Controllers\Auth.php(23): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: App\\Controllers\\Auth::$session', 'C:\\xampp\\htdocs\\codeigniter4\\app\\Controllers\\Auth.php', 23)
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-30 11:04:06 --> Undefined variable $session
in APPPATH\Controllers\Auth.php on line 23.
 1 APPPATH\Controllers\Auth.php(23): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $session', 'C:\\xampp\\htdocs\\codeigniter4\\app\\Controllers\\Auth.php', 23)
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-30 11:04:13 --> Undefined property: App\Controllers\Auth::$session
in APPPATH\Controllers\Auth.php on line 23.
 1 APPPATH\Controllers\Auth.php(23): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: App\\Controllers\\Auth::$session', 'C:\\xampp\\htdocs\\codeigniter4\\app\\Controllers\\Auth.php', 23)
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-30 11:05:58 --> Undefined property: App\Controllers\Auth::$session
in APPPATH\Controllers\Auth.php on line 23.
 1 APPPATH\Controllers\Auth.php(23): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: App\\Controllers\\Auth::$session', 'C:\\xampp\\htdocs\\codeigniter4\\app\\Controllers\\Auth.php', 23)
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-30 11:05:59 --> Undefined property: App\Controllers\Auth::$session
in APPPATH\Controllers\Auth.php on line 23.
 1 APPPATH\Controllers\Auth.php(23): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: App\\Controllers\\Auth::$session', 'C:\\xampp\\htdocs\\codeigniter4\\app\\Controllers\\Auth.php', 23)
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-30 11:06:11 --> Undefined property: App\Controllers\Auth::$session
in APPPATH\Controllers\Auth.php on line 23.
 1 APPPATH\Controllers\Auth.php(23): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: App\\Controllers\\Auth::$session', 'C:\\xampp\\htdocs\\codeigniter4\\app\\Controllers\\Auth.php', 23)
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-30 11:08:41 --> Undefined variable $config
in APPPATH\Controllers\Auth.php on line 14.
 1 APPPATH\Controllers\Auth.php(14): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $config', 'C:\\xampp\\htdocs\\codeigniter4\\app\\Controllers\\Auth.php', 14)
 2 SYSTEMPATH\CodeIgniter.php(906): App\Controllers\Auth->__construct()
 3 SYSTEMPATH\CodeIgniter.php(490): CodeIgniter\CodeIgniter->createController()
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-30 11:09:27 --> Undefined variable $session
in APPPATH\Controllers\Auth.php on line 25.
 1 APPPATH\Controllers\Auth.php(25): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $session', 'C:\\xampp\\htdocs\\codeigniter4\\app\\Controllers\\Auth.php', 25)
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-30 11:09:31 --> Undefined variable $session
in APPPATH\Controllers\Auth.php on line 25.
 1 APPPATH\Controllers\Auth.php(25): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $session', 'C:\\xampp\\htdocs\\codeigniter4\\app\\Controllers\\Auth.php', 25)
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-30 11:09:44 --> Undefined variable $session
in APPPATH\Controllers\Auth.php on line 25.
 1 APPPATH\Controllers\Auth.php(25): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $session', 'C:\\xampp\\htdocs\\codeigniter4\\app\\Controllers\\Auth.php', 25)
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-30 11:13:46 --> Call to undefined method CodeIgniter\View\View::session()
in APPPATH\Views\backend\login.php on line 13.
 1 SYSTEMPATH\View\View.php(213): include()
 2 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 3 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('backend/login', [], true)
 4 APPPATH\Controllers\Auth.php(29): view('backend/login', [...])
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-30 11:14:54 --> print_r() expects at least 1 argument, 0 given
in APPPATH\Views\backend\login.php on line 13.
 1 APPPATH\Views\backend\login.php(13): print_r()
 2 SYSTEMPATH\View\View.php(213): include('C:\\xampp\\htdocs\\codeigniter4\\app\\Views\\backend\\login.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('backend/login', [], true)
 5 APPPATH\Controllers\Auth.php(29): view('backend/login', [...])
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-30 11:14:55 --> print_r() expects at least 1 argument, 0 given
in APPPATH\Views\backend\login.php on line 13.
 1 APPPATH\Views\backend\login.php(13): print_r()
 2 SYSTEMPATH\View\View.php(213): include('C:\\xampp\\htdocs\\codeigniter4\\app\\Views\\backend\\login.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('backend/login', [], true)
 5 APPPATH\Controllers\Auth.php(29): view('backend/login', [...])
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-30 11:14:56 --> print_r() expects at least 1 argument, 0 given
in APPPATH\Views\backend\login.php on line 13.
 1 APPPATH\Views\backend\login.php(13): print_r()
 2 SYSTEMPATH\View\View.php(213): include('C:\\xampp\\htdocs\\codeigniter4\\app\\Views\\backend\\login.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('backend/login', [], true)
 5 APPPATH\Controllers\Auth.php(29): view('backend/login', [...])
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-30 11:14:56 --> print_r() expects at least 1 argument, 0 given
in APPPATH\Views\backend\login.php on line 13.
 1 APPPATH\Views\backend\login.php(13): print_r()
 2 SYSTEMPATH\View\View.php(213): include('C:\\xampp\\htdocs\\codeigniter4\\app\\Views\\backend\\login.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('backend/login', [], true)
 5 APPPATH\Controllers\Auth.php(29): view('backend/login', [...])
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-30 11:14:56 --> print_r() expects at least 1 argument, 0 given
in APPPATH\Views\backend\login.php on line 13.
 1 APPPATH\Views\backend\login.php(13): print_r()
 2 SYSTEMPATH\View\View.php(213): include('C:\\xampp\\htdocs\\codeigniter4\\app\\Views\\backend\\login.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('backend/login', [], true)
 5 APPPATH\Controllers\Auth.php(29): view('backend/login', [...])
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-30 11:15:41 --> Attempt to read property "user_password" on null
in APPPATH\Controllers\Auth.php on line 22.
 1 APPPATH\Controllers\Auth.php(22): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "user_password" on null', 'C:\\xampp\\htdocs\\codeigniter4\\app\\Controllers\\Auth.php', 22)
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-30 11:20:11 --> Undefined variable $data
in APPPATH\Controllers\Auth.php on line 35.
 1 APPPATH\Controllers\Auth.php(35): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $data', 'C:\\xampp\\htdocs\\codeigniter4\\app\\Controllers\\Auth.php', 35)
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->admin()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-30 11:24:51 --> view(): Argument #2 ($data) must be of type array, null given, called in C:\xampp\htdocs\codeigniter4\app\Controllers\Auth.php on line 27
in SYSTEMPATH\Common.php on line 1172.
 1 APPPATH\Controllers\Auth.php(27): view('backend/login', null)
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-30 11:25:12 --> view(): Argument #2 ($data) must be of type array, null given, called in C:\xampp\htdocs\codeigniter4\app\Controllers\Auth.php on line 27
in SYSTEMPATH\Common.php on line 1172.
 1 APPPATH\Controllers\Auth.php(27): view('backend/login', null)
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-30 11:26:07 --> view(): Argument #2 ($data) must be of type array, null given, called in C:\xampp\htdocs\codeigniter4\app\Controllers\Auth.php on line 27
in SYSTEMPATH\Common.php on line 1172.
 1 APPPATH\Controllers\Auth.php(27): view('backend/login', null)
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-30 11:27:11 --> Attempt to read property "user_password" on null
in APPPATH\Controllers\Auth.php on line 22.
 1 APPPATH\Controllers\Auth.php(22): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "user_password" on null', 'C:\\xampp\\htdocs\\codeigniter4\\app\\Controllers\\Auth.php', 22)
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-30 11:30:39 --> view(): Argument #2 ($data) must be of type array, null given, called in C:\xampp\htdocs\codeigniter4\app\Controllers\Auth.php on line 27
in SYSTEMPATH\Common.php on line 1172.
 1 APPPATH\Controllers\Auth.php(27): view('backend/login', null)
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-30 11:32:11 --> Attempt to read property "user_name" on array
in APPPATH\Controllers\Auth.php on line 22.
 1 APPPATH\Controllers\Auth.php(22): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "user_name" on array', 'C:\\xampp\\htdocs\\codeigniter4\\app\\Controllers\\Auth.php', 22)
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-30 11:32:21 --> syntax error, unexpected token "echo", expecting ";"
in APPPATH\Controllers\Auth.php on line 22.
 1 SYSTEMPATH\Autoloader\Autoloader.php(289): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs\\codeigniter4\\app\\Controllers\\Auth.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(267): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\Auth')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\Auth')
 4 SYSTEMPATH\CodeIgniter.php(892): class_exists('\\App\\Controllers\\Auth', true)
 5 SYSTEMPATH\CodeIgniter.php(486): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-30 11:32:35 --> Attempt to read property "user_name" on array
in APPPATH\Controllers\Auth.php on line 22.
 1 APPPATH\Controllers\Auth.php(22): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "user_name" on array', 'C:\\xampp\\htdocs\\codeigniter4\\app\\Controllers\\Auth.php', 22)
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-30 11:34:53 --> view(): Argument #2 ($data) must be of type array, null given, called in C:\xampp\htdocs\codeigniter4\app\Controllers\Auth.php on line 28
in SYSTEMPATH\Common.php on line 1172.
 1 APPPATH\Controllers\Auth.php(28): view('backend/login', null)
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-30 11:41:22 --> syntax error, unexpected token ";"
in APPPATH\Controllers\Auth.php on line 25.
 1 SYSTEMPATH\Autoloader\Autoloader.php(289): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs\\codeigniter4\\app\\Controllers\\Auth.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(267): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\Auth')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\Auth')
 4 SYSTEMPATH\CodeIgniter.php(892): class_exists('\\App\\Controllers\\Auth', true)
 5 SYSTEMPATH\CodeIgniter.php(486): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-30 11:41:47 --> Trying to access array offset on value of type null
in APPPATH\Controllers\Auth.php on line 22.
 1 APPPATH\Controllers\Auth.php(22): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to access array offset on value of type null', 'C:\\xampp\\htdocs\\codeigniter4\\app\\Controllers\\Auth.php', 22)
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-30 11:41:53 --> Trying to access array offset on value of type null
in APPPATH\Controllers\Auth.php on line 22.
 1 APPPATH\Controllers\Auth.php(22): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to access array offset on value of type null', 'C:\\xampp\\htdocs\\codeigniter4\\app\\Controllers\\Auth.php', 22)
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-30 12:39:36 --> Trying to access array offset on value of type null
in APPPATH\Controllers\Auth.php on line 22.
 1 APPPATH\Controllers\Auth.php(22): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to access array offset on value of type null', 'C:\\xampp\\htdocs\\codeigniter4\\app\\Controllers\\Auth.php', 22)
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-30 12:40:21 --> Trying to access array offset on value of type null
in APPPATH\Controllers\Auth.php on line 22.
 1 APPPATH\Controllers\Auth.php(22): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to access array offset on value of type null', 'C:\\xampp\\htdocs\\codeigniter4\\app\\Controllers\\Auth.php', 22)
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-30 12:41:07 --> Trying to access array offset on value of type null
in APPPATH\Controllers\Auth.php on line 23.
 1 APPPATH\Controllers\Auth.php(23): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to access array offset on value of type null', 'C:\\xampp\\htdocs\\codeigniter4\\app\\Controllers\\Auth.php', 23)
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-05-30 12:48:52 --> Error connecting to the database: mysqli_sql_exception: Hedef makine etkin olarak reddettiğinden bağlantı kurulamadı in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\codeigniter4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\codeigniter4\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\codeigniter4\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\codeigniter4\app\Controllers\Auth.php(22): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(934): App\Controllers\Auth->index()
#8 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\codeigniter4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Hedef makine etkin olarak reddettiğinden bağlantı kurulamadı in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\codeigniter4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\codeigniter4\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\codeigniter4\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#5 C:\xampp\htdocs\codeigniter4\app\Controllers\Auth.php(22): CodeIgniter\BaseModel->first()
#6 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(934): App\Controllers\Auth->index()
#7 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\codeigniter4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-05-30 12:48:52 --> Unable to connect to the database.
Main connection [MySQLi]: Hedef makine etkin olarak reddettiğinden bağlantı kurulamadı
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `user_name` = :user_name:
AND `users`.`deleted_at` IS NULL
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->doFirst()
 5 APPPATH\Controllers\Auth.php(22): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-05-30 12:48:56 --> Error connecting to the database: mysqli_sql_exception: Hedef makine etkin olarak reddettiğinden bağlantı kurulamadı in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\codeigniter4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\codeigniter4\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\codeigniter4\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\codeigniter4\app\Controllers\Auth.php(22): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(934): App\Controllers\Auth->index()
#8 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\codeigniter4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Hedef makine etkin olarak reddettiğinden bağlantı kurulamadı in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\codeigniter4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\codeigniter4\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\codeigniter4\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#5 C:\xampp\htdocs\codeigniter4\app\Controllers\Auth.php(22): CodeIgniter\BaseModel->first()
#6 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(934): App\Controllers\Auth->index()
#7 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\codeigniter4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2023-05-30 12:48:56 --> Error connecting to the database: mysqli_sql_exception: Hedef makine etkin olarak reddettiğinden bağlantı kurulamadı in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\codeigniter4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\codeigniter4\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\codeigniter4\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\codeigniter4\app\Controllers\Auth.php(22): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(934): App\Controllers\Auth->index()
#8 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\codeigniter4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Hedef makine etkin olarak reddettiğinden bağlantı kurulamadı in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\codeigniter4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\codeigniter4\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\codeigniter4\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#5 C:\xampp\htdocs\codeigniter4\app\Controllers\Auth.php(22): CodeIgniter\BaseModel->first()
#6 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(934): App\Controllers\Auth->index()
#7 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\codeigniter4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-05-30 12:48:56 --> Unable to connect to the database.
Main connection [MySQLi]: Hedef makine etkin olarak reddettiğinden bağlantı kurulamadı
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `user_name` = :user_name:
AND `users`.`deleted_at` IS NULL
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->doFirst()
 5 APPPATH\Controllers\Auth.php(22): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-30 12:48:56 --> Unable to connect to the database.
Main connection [MySQLi]: Hedef makine etkin olarak reddettiğinden bağlantı kurulamadı
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `user_name` = :user_name:
AND `users`.`deleted_at` IS NULL
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->doFirst()
 5 APPPATH\Controllers\Auth.php(22): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-05-30 12:49:00 --> Error connecting to the database: mysqli_sql_exception: Hedef makine etkin olarak reddettiğinden bağlantı kurulamadı in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\codeigniter4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\codeigniter4\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\codeigniter4\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\codeigniter4\app\Controllers\Auth.php(22): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(934): App\Controllers\Auth->index()
#8 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\codeigniter4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Hedef makine etkin olarak reddettiğinden bağlantı kurulamadı in C:\xampp\htdocs\codeigniter4\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\codeigniter4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\codeigniter4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\codeigniter4\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\codeigniter4\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#5 C:\xampp\htdocs\codeigniter4\app\Controllers\Auth.php(22): CodeIgniter\BaseModel->first()
#6 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(934): App\Controllers\Auth->index()
#7 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\codeigniter4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-05-30 12:49:00 --> Unable to connect to the database.
Main connection [MySQLi]: Hedef makine etkin olarak reddettiğinden bağlantı kurulamadı
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `user_name` = :user_name:
AND `users`.`deleted_at` IS NULL
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->doFirst()
 5 APPPATH\Controllers\Auth.php(22): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-30 14:36:21 --> Undefined property: App\Controllers\Auth::$template_folder
in APPPATH\Controllers\Auth.php on line 31.
 1 APPPATH\Controllers\Auth.php(31): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: App\\Controllers\\Auth::$template_folder', 'C:\\xampp\\htdocs\\codeigniter4\\app\\Controllers\\Auth.php', 31)
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-30 14:36:23 --> Undefined property: App\Controllers\Auth::$template_folder
in APPPATH\Controllers\Auth.php on line 31.
 1 APPPATH\Controllers\Auth.php(31): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: App\\Controllers\\Auth::$template_folder', 'C:\\xampp\\htdocs\\codeigniter4\\app\\Controllers\\Auth.php', 31)
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-30 14:38:34 --> Undefined property: App\Controllers\Auth::$template_folder
in APPPATH\Controllers\Auth.php on line 31.
 1 APPPATH\Controllers\Auth.php(31): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: App\\Controllers\\Auth::$template_folder', 'C:\\xampp\\htdocs\\codeigniter4\\app\\Controllers\\Auth.php', 31)
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-30 14:38:35 --> Undefined property: App\Controllers\Auth::$template_folder
in APPPATH\Controllers\Auth.php on line 31.
 1 APPPATH\Controllers\Auth.php(31): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: App\\Controllers\\Auth::$template_folder', 'C:\\xampp\\htdocs\\codeigniter4\\app\\Controllers\\Auth.php', 31)
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-30 14:38:36 --> Undefined property: App\Controllers\Auth::$template_folder
in APPPATH\Controllers\Auth.php on line 31.
 1 APPPATH\Controllers\Auth.php(31): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: App\\Controllers\\Auth::$template_folder', 'C:\\xampp\\htdocs\\codeigniter4\\app\\Controllers\\Auth.php', 31)
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-30 14:39:13 --> Undefined variable $base_url
in APPPATH\Controllers\Auth.php on line 31.
 1 APPPATH\Controllers\Auth.php(31): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $base_url', 'C:\\xampp\\htdocs\\codeigniter4\\app\\Controllers\\Auth.php', 31)
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-30 14:39:14 --> Undefined variable $base_url
in APPPATH\Controllers\Auth.php on line 31.
 1 APPPATH\Controllers\Auth.php(31): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $base_url', 'C:\\xampp\\htdocs\\codeigniter4\\app\\Controllers\\Auth.php', 31)
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->index()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-30 14:49:56 --> Too few arguments to function App\Libraries\Twig\Twig::render(), 1 passed in C:\xampp\htdocs\codeigniter4\app\Controllers\Auth.php on line 42 and exactly 2 expected
in APPPATH\Libraries\Twig\Twig.php on line 101.
 1 APPPATH\Controllers\Auth.php(42): App\Libraries\Twig\Twig->render('backend/admin')
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->admin()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-30 14:50:30 --> Too few arguments to function App\Libraries\Twig\Twig::render(), 1 passed in C:\xampp\htdocs\codeigniter4\app\Controllers\Auth.php on line 42 and exactly 2 expected
in APPPATH\Libraries\Twig\Twig.php on line 101.
 1 APPPATH\Controllers\Auth.php(42): App\Libraries\Twig\Twig->render('backend/admin')
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->admin()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-30 14:50:36 --> Too few arguments to function App\Libraries\Twig\Twig::render(), 1 passed in C:\xampp\htdocs\codeigniter4\app\Controllers\Auth.php on line 42 and exactly 2 expected
in APPPATH\Libraries\Twig\Twig.php on line 101.
 1 APPPATH\Controllers\Auth.php(42): App\Libraries\Twig\Twig->render('backend/admin')
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->admin()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-30 14:51:19 --> Too few arguments to function App\Libraries\Twig\Twig::render(), 1 passed in C:\xampp\htdocs\codeigniter4\app\Controllers\Auth.php on line 42 and exactly 2 expected
in APPPATH\Libraries\Twig\Twig.php on line 101.
 1 APPPATH\Controllers\Auth.php(42): App\Libraries\Twig\Twig->render('backend/admin')
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->admin()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-30 14:51:21 --> Too few arguments to function App\Libraries\Twig\Twig::render(), 1 passed in C:\xampp\htdocs\codeigniter4\app\Controllers\Auth.php on line 42 and exactly 2 expected
in APPPATH\Libraries\Twig\Twig.php on line 101.
 1 APPPATH\Controllers\Auth.php(42): App\Libraries\Twig\Twig->render('backend/admin')
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->admin()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-30 14:51:22 --> Too few arguments to function App\Libraries\Twig\Twig::render(), 1 passed in C:\xampp\htdocs\codeigniter4\app\Controllers\Auth.php on line 42 and exactly 2 expected
in APPPATH\Libraries\Twig\Twig.php on line 101.
 1 APPPATH\Controllers\Auth.php(42): App\Libraries\Twig\Twig->render('backend/admin')
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->admin()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-30 14:52:23 --> Too few arguments to function App\Libraries\Twig\Twig::render(), 1 passed in C:\xampp\htdocs\codeigniter4\app\Controllers\Auth.php on line 42 and exactly 2 expected
in APPPATH\Libraries\Twig\Twig.php on line 101.
 1 APPPATH\Controllers\Auth.php(42): App\Libraries\Twig\Twig->render('backend/admin')
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->admin()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-30 14:52:58 --> Too few arguments to function App\Libraries\Twig\Twig::render(), 1 passed in C:\xampp\htdocs\codeigniter4\app\Controllers\Auth.php on line 42 and exactly 2 expected
in APPPATH\Libraries\Twig\Twig.php on line 101.
 1 APPPATH\Controllers\Auth.php(42): App\Libraries\Twig\Twig->render('backend/admin')
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Auth->admin()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
